### ISSUE TITLE
No handler for Eoddata Response message MSG_NO_DATA_AVAILABLE

### ISSUE THREAD

**Issue by Jcerwin** [apologist/eoddata-client#2]
Fixed in **eoddata_client.py**, but cannot upload a file or issue a pull request in this repository.

Add a new message type: 
`MSG_NO_DATA_AVAILABLE = 'No data available'`

Add a new Error class: 
`class NoDataAvailableError(Error):`

Update  `def process_response` to include 
```
elif message == MSG_NO_DATA_AVAILABLE:
        raise NoDataAvailableError(message);
```

**Comment by apologist** [comment]
Thank You! I apologize for so slow response. Will fix it in the next few days. Take a look [here](https://help.github.com/articles/creating-a-pull-request/) about pull requests.
