### ISSUE TITLE
Fail to login

### ISSUE THREAD

**Issue by fulifeng** [apologist/eoddata-client#3]
Thanks for the code. Could you please let me know whether this code is still working now? I try to use this code to access data from EODDATA, but it always fails to login and replies "Invalid Username or Password", which I'm sure is correct and works well when login through browser.

**Comment by apologist** [comment]
Hello, sorry for the slow response, I have just tested - it works fine. Did You try to log in here - http://ws.eoddata.com/data.asmx?op=Login? Do you have a Platinum subscription? - since You can get access to data through web service only with such subscription.
