### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by ghost** [apologist/eoddata-client#4]

**Comment by apologist** [comment]
@JeremieGauthier Thank You, make pull requests if You work with EodData and need changes since I don't use this service anymore.

**Comment by ghost** [comment]
Which service do you use now?

**Comment by apologist** [comment]
@JeremieGauthier I am not in trading right now. Actually, a company I was working for almost did not use historical data, when needed - Interactive Brokers have enough quota for viewing historical data. Used EodData for my coursework and unfortunately during that period a company had troubles with SEC and we stopped trading, then I lost my interest. 
If You are looking for historical data, look through these services:
- Enterprise:
  - Morningstar
  - Thomson Reuters
  - Bloomberg Professional Services
- Retail, different types of subscriptions, some data is free:
  - Factset
  - S&P Capital IQ
  - Center for Research in Security Prices
  - Portara CQG
  - Tick Data
  - Algoseek
  - IQ Feed (good price / value)
  - Tick data market
  - Xignite
  - QuantQuote
  - Nanex
  - QuantGo
  - TradeStation
  - Commodity Systems
  - CME Group
  - Olsen Data
  - Six Financial Information
  - E-Signal
  - MetaStock
  - Eze Software Group
  - Interactive Data
  - MTS Data
  - Premium Data
  - One Market Data
  - Bar Chart
  - Historical Option Data
  - Optionistics
  - CBOE LIVEVOL Data
  - IVolatility
  - Dukascopy (partly free)
  - Quandl (partly free)

**Comment by ghost** [comment]
Eoddata is still given services, so your wrapper is very useful. I got a bit of difficulty at the beginning because only 20 requests were accepted amongst 10,000. I realize that we could use max_login_retries=### inside EodDataHttpClient(username, password, max_login_retries=10000). Furthermore, it wasn't really fast, so multithreading was required.
